name: Maven Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version de release (ex: 1.2.3)'
        required: true
      developmentVersion:
        description: 'Prochaine version de développement (ex: 1.2.4-SNAPSHOT)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: maven

      - name: Build avec Maven
        run: mvn -B clean verify
        
      - name: Configurer Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TESTKEY }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: maven
          server-id: github
  
      - name: Configurer Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
  
      - name: Préparer la release
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
          git commit -am "Prépare la release ${{ github.event.inputs.releaseVersion }}"
          git tag -a v${{ github.event.inputs.releaseVersion }} -m "Version ${{ github.event.inputs.releaseVersion }}"
  
      - name: Build et publier
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TESTKEY }}
  
      - name: Préparer la prochaine version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.developmentVersion }}
          git commit -am "Prépare pour la prochaine version de développement"
          git push
          git push --tags
  
      - name: Créer la GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.releaseVersion }}
          name: Release ${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.TESTKEY }}
  auto-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TESTKEY }}

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: maven
          server-id: github
  
      - name: Configurer Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Récupérer la version actuelle
        id: get_version
        run: |
          # Extraire la version actuelle du POM
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          # Vérifier si c'est une version SNAPSHOT
          if [[ $CURRENT_VERSION == *-SNAPSHOT ]]; then
            # Enlever le suffixe SNAPSHOT pour la version de release
            RELEASE_VERSION=${CURRENT_VERSION%-SNAPSHOT}
            # Incrémenter le numéro de version pour la prochaine version de développement
            IFS='.' read -ra VERSION_PARTS <<< "$RELEASE_VERSION"
            PATCH_VERSION=$((VERSION_PARTS[2] + 1))
            NEXT_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${PATCH_VERSION}-SNAPSHOT"
            
            echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
            echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
            echo "is_snapshot=true" >> $GITHUB_OUTPUT
          else
            echo "is_snapshot=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Préparer la release
        if: steps.get_version.outputs.is_snapshot == 'true'
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.release_version }}
          git commit -am "Prépare la release ${{ steps.get_version.outputs.release_version }}"
          git tag -a v${{ steps.get_version.outputs.release_version }} -m "Version ${{ steps.get_version.outputs.release_version }}"
      
      - name: Build et publier
        if: steps.get_version.outputs.is_snapshot == 'true'
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Préparer la prochaine version
        if: steps.get_version.outputs.is_snapshot == 'true'
        run: |
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.next_version }}
          git commit -am "Prépare pour la prochaine version de développement"
          git push
          git push --tags
      
      - name: Créer la GitHub Release
        if: steps.get_version.outputs.is_snapshot == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.release_version }}
          name: Release ${{ steps.get_version.outputs.release_version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.TESTKEY }}


  
  release-from-tag:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: maven
          server-id: github
  
      - name: Build et publier
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TESTKEY }}
  
      - name: Créer la GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.TESTKEY }}
